
[[identifier]]
== Identifier

[[target-system]]
=== Target System

The target system of the `did:swid` DID method is a registry known as Spatial Web
SWID Registry, which is managed by a Designated Authority.

[[method-name]]
=== Method Name

The namestring that identifies this DID method is: `swid`. A DID that uses this method
MUST begin with the following prefix: `did:swid`. Per the DID specification, this
string MUST be in lowercase. The remainder of the DID, after the prefix, is the <<method-specific-identifier>>, specified below.

[[method-specific-identifier]]
=== Method-Specific Identifier

The `did:swid` method-specific identifier contains a {{self-certifying identifier,options="linkmention,linkref"}}
(SCID) for the DID.

As specified in the following Augmented Backus-Naur Form (ABNF) notation <<RFC2234>>
the {{self-certifying identifier,SCID,options="linkmention,linkref"}} *MUST* be present
in the DID string. See examples below.

[source%unnumbered,json]
----
swid-did = "did:swid:" "z" scid
scid = 46(base58-btc-alphabet) 

----

The `scid` part of the `did:swid` identifier is generated by creating a cryptographic
digest (hash) of the first entry of a data structure known as
https://digitalbazaar.github.io/cel-spec/#the-did-document-cel-specification[Cryptographic Event Log]
(also see <<the-swid-registry>>). The hash is encoded using {{multihash,options="linkmention,linkref"}}.

The characters in the `base58-btc-alphabet` are as defined in the W3C
https://www.w3.org/TR/cid-1.0/#multibase-0[Controller Documents] specification.

Example `did:swid`:

[source%unnumbered,json]
----
did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv
----
