
[[identifier]]
== Identifier

[[target-system]]
=== Target system

The target system of the `did:swid` DID method is a registry known as Spatial Web
SWID Registry, which is managed by a Designated Authority.

[[method-name]]
=== Method name

The namestring that identifies this DID method is: `swid`. A DID that uses this
method MUST begin with the following prefix: `did:swid`. Per the DID
specification, this string MUST be in lowercase. The remainder of the DID, after
the prefix, is the <<method-specific-identifier>>, specified below.

[[method-specific-identifier]]
=== Method-specific identifier

The `did:swid` method-specific identifier contains a self-certifying identifier
(SCID) for the DID.

As specified in the following Augmented Backus-Naur Form (ABNF) notation
<<RFC2234>> the self-certifying identifier *MUST* be present in the DID string.
See examples below.

.Example method-specific identifier
[example]
====
[source,json]
----
swid-did = "did:swid:" "z" scid
scid = 46(base58-btc-alphabet)
----
====

The `scid` part of the `did:swid` identifier is generated by creating a
cryptographic digest (hash) of the first entry of a data structure known as
Cryptographic Event Log <<cel-spec>> (also see <<the-swid-registry>>). The hash
is encoded using multihash (<<MULTIFORMATS>>).

The characters in the `base58-btc-alphabet` are as defined in the W3C
Controller Documents specification (<<w3c_cid-10>>).

.Example `did:swid`
[example]
====
[source,json]
----
did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv
----
====
