
[[did-method-operations]]
== DID Method Operations

[[create-register]]
=== Create (Register)

[[creating-a-didswid]]
==== Creating a `did:swid`

To create a `did:swid`, the Entity first generates a private/public key pair that
controls the DID. The public key is included as a verification method in the initial
version of the DID document.

This initial version of the DID document MUST be a conformant SWID Document, i.e.
it MUST have an HSTP Service Endpoint.

See <<SWIDS-AND-SWID-DOCUMENTS>> for more details about SWIDs and SWID Documents.

.Example initial DID document
[example]
====
[source,json]
----
{
   "@context": [
      "https://www.w3.org/ns/did/v1.1",
      "https://spatialwebfoundation.org/contexts/did/1.0"
   ],
   "verificationMethod": [{
      "id": "#keys-1",
      "type": "Multikey",
      "publicKeyMultibase": "z6MkmM42vxfqZQsv4ehtTjFFxQ4sQKS2w6WR7emozFAn5cxu"
   }],
   "authentication": [
     "#keys-1"
   ],
   "service": [{
      "id": "#hstp",
      "type": "HSTPEndpoint",
      "serviceEndpoint": "https://hstp.example.com/hstpendpoint"
   }]
}
----
====

Using the initial version of the DID document, the first entry of a
Cryptographic Event Log (<<cel-spec>>) is constructed (also see
<<the-swid-registry>>). A cryptographic digest (hash) of this entry is created
and encoded using multihash (<<MULTIFORMATS>>), and is used as the `scid` part
of the `did:swid` identifier (see <<identifier>>).

.Example SWID
[example]
====
[source,json]
----
did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv
----
====

[[using-a-did-issuer-service]]
==== Using a DID Issuer Service

A `did:swid` or other type of SWID may be created by a "DID Issuer Service" at behest
of the Entity.

The following diagram describes the process of creating a SWID using a
"DID Issuer Service":

.Creating a SWID using a DID Issuer Service
plantuml_image::./plantuml/creating-a-swid-using-a-did-issuer-service.puml[]

When creating a `did:swid` or other type of SWID, the "DID Issuer Service" MUST enforce
that the DID document associated with the SWID is a conformant SWID Document, i.e.
it MUST have an HSTP Service Endpoint. Otherwise, the "DID Issuer Service" MUST return
an error response.

See <<SWIDS-AND-SWID-DOCUMENTS>> for more details about SWIDs and SWID Documents.

To create a SWID using a "DID Issuer Service", the `create` function of the DIF
specification (<<DID-REGISTRATION>>) is used.

.Example Request to create a SWID
[example]
====
HTTP POST to identifier:[https://<did-issuer>/create?method=swid]

[source,json]
----
{
  "options": {
    "clientSecretMode": true
  },
  "secret": { },
  "didDocument": {
     "@context": [
        "https://www.w3.org/ns/did/v1.1",
        "https://spatialwebfoundation.org/contexts/did/1.0"
     ],
     "verificationMethod": [{
        "id": "#keys-1",
        "type": "Multikey",
        "publicKeyMultibase": "z6MkmM42vxfqZQsv4ehtTjFFxQ4sQKS2w6WR7emozFAn5cxu"
     }],
     "authentication": [
       "#keys-1"
     ],
     "service": [{
        "id": "#hstp",
        "type": "HSTPEndpoint",
        "serviceEndpoint": "https://hstp.example.com/hstpendpoint"
     }]
  }
}
----
====


.Example Response
[example]
====
[source,json]
----
{
  "didState": {
    "state": "finished",
    "did": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv",
    "secret": { }
  },
  "didRegistrationMetadata": { },
  "didDocumentMetadata": { }
}
----
====

During the process of creating a SWID, the Entity MAY be required to prove
control of its SWID's associated public key, using Signing Requests
(<<DID-REGISTRATION>>) and Signing Responses (<<DID-REGISTRATION>>).

.Example Signing Request
[example]
====
[source,json]
----
{
	"jobId": "96202012-41d8-424a-85a9-3673bda6abc7",
	"didState": {
		"state": "action",
		"action": "signPayload",
		"signingRequest": {
			"signingRequestCreate": {
				"kid": "#keys-1",
				"alg": "EdDSA",
				"purpose": "authentication",
				"serializedPayload": "<-- base 64 encoded -->"
			}
		}
	},
	"didRegistrationMetadata": { ... },
	"didDocumentMetadata": { ... }
}
----
====

.Example Signing Response
[example]
====
[source,json]
----
{
    "jobId": "96202012-41d8-424a-85a9-3673bda6abc7",
    "options": {
        "clientSecretMode": true
    },
    "secret": {
        "signingResponse": {
            "signingRequestCreate": {
                "signature": "<-- base64 encoded -->"
            }
        }
    },
    "didDocument": {}
}
----
====

[[read-resolve]]
=== Read (Resolve)

To resolve a `did:swid` or other type of SWID, the `resolve` function
<<DID-RESOLUTION>> is used.

.Example Request to resolve a SWID
[example]
====
HTTP GET to identifier:[https://<swid-resolver>/identifiers/did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv]
====

.Example Response
[example]
====
[source,json]
----
{
  "didDocument": {
    "@context": [
      "https://www.w3.org/ns/did/v1.1",
      "https://spatialwebfoundation.org/contexts/did/1.0"
    ],
    "id": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv",
    "verificationMethod": [{
      "id": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv#keys-1",
      "type": "Multikey",
      "controller": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv",
      "publicKeyMultibase": "z6MkmM42vxfqZQsv4ehtTjFFxQ4sQKS2w6WR7emozFAn5cxu"
    }],
    "authentication": [
      "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv#keys-1"
    ],
    "service": [{
      "id": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv#hstp",
      "type": "HSTPEndpoint",
      "serviceEndpoint": "https://hstp.example.com/hstpendpoint"
    }]
  },
  "didResolutionMetadata": { },
  "didDocumentMetadata": { }
}
----
====

[[update-rotate]]
=== Update (Rotate)

To update a `did:swid` or other type of SWID, the `update` function
<<DID-REGISTRATION>> is used.

Updating a SWID can include the following:

* Rotating the public key that controls the SWID.
* Changing the HSTP service endpoint of the SWID.

.Example Request to update a SWID
[example]
====
HTTP POST to identifier:[https://<swid-registry>/update]

[source,json]
----
{
  "did": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv",
  "options": {
    "clientSecretMode": true
  },
  "secret": { },
   "didDocument": {
      "@context": [
         "https://www.w3.org/ns/did/v1.1",
         "https://spatialwebfoundation.org/contexts/did/1.0"
      ],
      "id": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv",
      "verificationMethod": [{
         "id": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv#keys-1",
         "type": "Multikey",
         "controller": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv",
         "publicKeyMultibase": "z6MkmM42vxfqZQsv4ehtTjFFxQ4sQKS2w6WR7emozFAn5cxu"
      }],
      "authentication": [
         "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv#keys-1"
      ],
      "service": [{
         "id": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv#hstp",
         "type": "HSTPEndpoint",
         "serviceEndpoint": "https://hstp.example.com/new_hstpendpoint"
      }]
   }
}
----
====

.Example Response
[example]
====
[source,json]
----
{
  "didState": {
    "state": "finished",
    "did": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv",
    "secret": { }
  },
  "didRegistrationMetadata": { },
  "didDocumentMetadata": { }
}
----
====

During the process of updating a SWID, the Entity MAY be required to prove control
of its SWID's associated public key, using
https://identity.foundation/did-registration/#signing-request-set[Signing Requests]
and https://identity.foundation/did-registration/#signing-response-set[Signing Responses].

[[deactivate-revoke]]
=== Deactivate (Revoke)

To deactivate a `did:swid` or other type of SWID, the `deactivate` function of
the DIF <<DID-REGISTRATION>> specification is used.

.Example Request to deactivate a SWID
[example]
====
HTTP POST to identifier:[https://<swid-registry>/deactivate]

[source,json]
----
{
  "did": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv",
  "options": {
    "clientSecretMode": true
  },
  "secret": { }
}
----
====

.Example Response
[example]
====
[source,json]
----
{
  "didState": {
    "state": "finished",
    "did": "did:swid:zQmQoeG7u6XBtdXoek5p3aPoTjaSRemHAKrMcY2Hcjpe3jv",
    "secret": { }
  },
  "didRegistrationMetadata": { },
  "didDocumentMetadata": { }
}
----
====

During the process of deactivating a SWID, the Entity MAY be required to prove
control of its SWID's associated public key, using Signing Requests
(<<DID-REGISTRATION>>) and Signing Responses (<<DID-REGISTRATION>>).
