
[heading=terms and definitions]
== Definitions

=== self-certifying identifier
admitted:[SCID]

An object identifier derived from initial data such that an attacker could not create
a new object with the same identifier.

=== Data Integrity

https://www.w3.org/community/reports/credentials/CG-FINAL-data-integrity-20220722/[W3C Data Integrity]
is a specification of mechanisms for ensuring the authenticity and integrity of structured
digital documents using cryptography, such as digital signatures and other digital
mathematical proofs.

=== Decentralized Identifier

Decentralized Identifiers (DIDs) <<DID-CORE>> are a type of identifier that enable
verifiable, decentralized digital identities. A DID refers to any subject (e.g.,
a person, organization, thing, data model, abstract entity, etc.) as determined by
the controller of the DID.

=== DID Controller

The entity that controls (create, updates, deletes) a given DID, as defined in the
<<DID-CORE>>.

=== DID Document

A DID Document as defined by the <<DID-CORE>> -- the document returned when a DID
is resolved.

=== DID Method

DID methods are the mechanism by which a particular type of DID and its associated
DID document are created, resolved, updated, and deactivated. DID methods are defined
using separate DID method specifications.

=== ISO8601

A date/time expressed using the https://en.wikipedia.org/wiki/ISO_8601[ISO8601 Standard].

=== JSON Canonicalization Scheme

<<RFC8785>> defines a method for canonicalizing a JSON structure such that is suitable
for verifiable hashing or signing.

=== multibase

A specification for encoding binary data as a string using a prefix that indicates
the encoding.

=== multikey

A verification method that encodes key types into a single binary stream that is
then encoded as a <<multibase,multibase>> value.

=== multihash

Per the <<MULTIFORMATS>>, multihash is a specification for differentiating instances
of hashes. Software creating a hash prefixes (according to the specification) data
to the hash indicating the algorithm used and the length of the hash, so that software
receiving the hash knows how to verify it. Although multihash supports many hash
algorithms, for interoperability, <<did-controllers,DID Controllers>> *MUST* only
use the hash algorithms defined in this specification as permitted.

=== W3C VCDM

A Verifiable Credential that uses the Data Model defined by the W3C [[spec: W3C-VC]]
specification.
