@startuml

title Creating a SWID using a DID Issuer Service

actor       "Entity" as E
participant "Entity Wallet" as EW
participant "DID Issuer Service" as DI
database    "DID Method" as DM

E -> EW : Create SWID (DID)
EW -> EW : Create and store\nprivate/public key pair 
EW -> DI : Request DID
DI <-> EW : Prove control of DID\nsigning requests/responses
DI -> DM : Write DID
DM -> DI : DID
DI -> EW : DID
EW -> E : SWID (DID)

@enduml
